# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "dependabot(github-actions)"
      include: "scope"
    directories:
      - "/"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"

  # # Docker updates
  # - package-ecosystem: "docker"
  #   commit-message:
  #     prefix: "dependabot(docker)"
  #     include: "scope"
  #   directories:
  #     - "/"
  #   labels:
  #     - "dependencies"
  #     - "docker"
  #   open-pull-requests-limit: 10
  #   schedule:
  #     interval: "daily"

  # Go modules updates
  - package-ecosystem: "gomod"
    commit-message:
      prefix: "dependabot(gomod)"
      include: "scope"
    directories:
      - "/"
    labels:
      - "dependencies"
      - "gomod"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"

  # # Enable version updates for npm
  # - package-ecosystem: "npm"
  #   commit-message:
  #     prefix: "dependabot(npm)"
  #     include: "scope"
  #   directories:
  #     - "/"
  #   ignore:
  #     # Ignore major version updates for now
  #     - dependency-name: "*"
  #       update-types: ["version-update:semver-major"]
  #   labels:
  #     - "dependencies"
  #     - "npm"
  #   open-pull-requests-limit: 10
  #   schedule:
  #     interval: "daily"

  # # Terraform updates
  # - package-ecosystem: "terraform"
  #   commit-message:
  #     prefix: "dependabot(terraform)"
  #     include: "scope"
  #   directories:
  #     - "/"
  #   labels:
  #     - "dependencies"
  #     - "terraform"
  #   open-pull-requests-limit: 10
  #   schedule:
  #     interval: "daily"
