# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: README.*.md
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
  # for go
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go.
        entry: golangci-lint run --max-same-issues=0 --max-issues-per-linter=0 --config=.golangci.yaml --fix
        types: [go]
        language: golang
        exclude: ^.*_test.go$
        pass_filenames: false
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id:
          detect-secrets
          # args: ['--baseline', '.secrets.baseline']
          # exclude: package.lock.json
  - repo: https://github.com/zricethezav/gitleaks
    rev: v7.6.0
    hooks:
      - id: gitleaks
